#! /usr/bin/python
#coding=UTF-8
#
# Copyright © 2015 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
import cairo,pango,pangocairo
from datetime import date

class Backup(object):
    """Representation of a single backup"""
    def __init__(self,host,volume,device,time,status):
        self.host=host
        self.volume=volume
        self.device=device
        self.time=time
        self.status=status

class Backups(object):
    """Representation of all backups"""
    def __init__(self, db="/home/richard/backups.db"):
        """Load the list of backups

        Arguments:
        db -- database path
        """
        self.db=db
        self.conn=None
        self.font=pango.FontDescription("sans 10")
        self.xpad=8
        self.ypad=2
        self.background_color=(1,1,1)
        self.foreground_color=(0,0,0)
        self.stripe_color=(0.9375,0.9375,0.9375)
        self.device_colors=[(1,0,0),
                            (0,1,0),
                            (0,0.125,1),
                            (1,0,1),
                            (1,1,0.25)]
        self.day_width=4
        self.device_indicator_height=2
        self.device_key_indicator_width=16
        self._retrieve()

    # Backup loading and analysis

    def _conn(self):
        """Return a connection to the database"""
        if self.conn is None:
            import sqlite3
            self.conn=sqlite3.connect(self.db)
        return self.conn

    def _retrieve(self):
        """Load self up with complete backups

        Initializes:
        backups -- the list of backups, in no particular order"""
        c=self._conn().cursor()
        backups=[]
        for row in c.execute(
                "SELECT host,volume,device,time,status FROM backup"):
            backup=Backup(*tuple(row))
            if backup.status==2:
                backups.append(backup)
        self.backups=backups

    def _ranges(self):
        """Analyse backups

        Initializes:
        hv_to_row -- dict mapping host:volume to a row number (from 0)
        device_list -- list of devices in order
        device_to_index -- dict mapping device to a color number (from 0)
        """
        hv_dict={}
        device_dict={}
        for backup in self.backups:
            hv_dict["%s:%s" % (backup.host, backup.volume)] = True
            device_dict[backup.device]=True
        # TODO also, volumes from config, so we can see things with no
        # backups
        # Put volumes into a coherent order
        hv_list=list(hv_dict.keys())
        hv_list.sort()
        # Map volume identification to row number
        row=0
        self.hv_to_row={}
        for hv in hv_list:
            self.hv_to_row[hv]=row
            row+=1
        # Map device names to an index
        self.device_list=list(device_dict.keys())
        self.device_list.sort()
        device_index=0
        self.device_to_index={}
        for device in self.device_list:
            self.device_to_index[device]=device_index
            device_index+=1

    # Text handling

    def _text_extent(self, c, t):
        """Return text extents

        Arguments:
        c -- cairo context
        t -- text to analyze

        Returns ink, logical where each is (x,y,w,h)."""
        layout=c.create_layout()
        layout.set_text(t)
        layout.set_font_description(self.font)
        return layout.get_pixel_extents()

    def _text(self, c, x, y, t):
        """Render text

        Arguments:
        c -- cairo context
        x -- top left x coordinate
        y -- top left y coordinate
        t -- text to render

        Returns text extents as ink, logical where each is (x,y,w,h)."""
        layout=c.create_layout()
        layout.set_text(t)
        layout.set_font_description(self.font)
        c.move_to(x, y)
        c.show_layout(layout)
        return layout.get_pixel_extents()

    def _extents_row_labels(self, c):
        """Calculate row label extents

        Arguments:
        c -- cairo context

        Initializes:
        host_width -- width of the host labels
        volume_width -- width of the volume labels
        row_height -- height of a row
        """
        self.host_width=0
        self.volume_width=0
        self.row_height=len(self.device_to_index)*self.device_indicator_height
        for volume in self.hv_to_row:
            host,volume=volume.split(':')
            i,l=self._text_extent(c, host)
            if l[2] > self.host_width: self.host_width=l[2]
            if l[3] > self.row_height: self.row_height=l[3]
            i,l=self._text_extent(c, volume)
            if l[2] > self.volume_width: self.volume_width=l[2]
            if l[3] > self.row_height: self.row_height=l[3]
        self.host_width+=self.xpad
        self.volume_width+=self.xpad
        self.row_height+=self.ypad

    def _extents_rows(self, c):
        """Calculate row layout extents

        Arguments:
        c -- cairo context

        Initializes:
        min_ordinal -- earliest day number
        max_ordinal -- latest day numer
        date_label_height -- height of date labels
        row_width -- total width of rows
        rows_height -- total height of row layout
        """
        self.min_ordinal=0xFFFFFFFFFFFFFFFF
        self.max_ordinal=0
        self.date_label_height=0
        for backup in self.backups:
            d=date.fromtimestamp(backup.time)
            o=d.toordinal()
            if o < self.min_ordinal: self.min_ordinal=o
            if o > self.max_ordinal: self.max_ordinal=o
            i,l=self._text_extent(c, d.isoformat())
            if l[3] > self.date_label_height: self.date_label_height=l[3]
        self.days=self.max_ordinal - self.min_ordinal+1
        self.row_width=self.day_width*self.days
        self.rows_height=len(self.hv_to_row)*self.row_height

    def _extents_device_key(self, c):
        """Calculate device key extents

        Arguments:
        c -- cairo context

        Initializes:
        max_device_width -- maximum width of a device name
        max_device_height -- maximum height of a device name
        device_key_width -- width of device key
        device_key_height -- height of device key
        """
        self.max_device_width=0
        self.max_device_height=0
        for device in self.device_list:
            i,l=self._text_extent(c, device)
            if l[2] > self.max_device_width: self.max_device_width=l[2]
            if l[3] > self.max_device_height: self.max_device_height=l[3]
        self.device_key_width=(self.max_device_width
                               + self.xpad
                               + self.device_key_indicator_width)
        self.device_key_height=self.max_device_height * len(self.device_list)
        
    def _extents_total(self, c):
        """Calculate total extents

        Arguments:
        c -- cairo context

        Initializes:
        days_start -- x coordinate of the first day's column
        device_key_x -- top left of device key
        device_key_y -- top left of device key
        total_width -- image width
        total_height -- image height
        """
        self.days_start=self.host_width+self.volume_width
        self.total_width=self.days_start+self.row_width
        self.device_key_x=self.total_width-self.device_key_width
        self.device_key_y=(self.rows_height+self.ypad
                           +self.date_label_height+self.ypad)
        self.total_height=self.device_key_y+self.device_key_height

    def _render_background(self, c):
        """Render the background

        Arguments:
        c -- cairo context"""
        c.rectangle(0,0,self.total_width,self.total_height)
        c.set_source_rgb(*self.background_color)
        c.fill()

    def _render_row_labels(self, c):
        """Render the row labels

        Arguments:
        c -- cairo context"""
        c.set_source_rgb(*self.foreground_color)
        for hv in self.hv_to_row:
            host,volume=hv.split(':')
            row=self.hv_to_row[hv]
            self._text(c, 0, row * self.row_height, host)
            self._text(c, self.host_width, row * self.row_height, volume)

    def _render_date_bars(self, c):
        """Render the date bars

        Arguments:
        c -- cairo context"""
        c.set_source_rgb(*self.stripe_color)
        x=self.host_width+self.volume_width
        for o in range(self.min_ordinal, self.max_ordinal+1, 2):
            c.rectangle(x,0,self.day_width,self.rows_height)
            x+=self.day_width*2
        c.fill()

    def _render_date_labels(self, c):
        """Render the date labels

        Arguments:
        c -- cairo context"""
        c.set_source_rgb(*self.foreground_color)
        x=self.host_width+self.volume_width
        y=self.rows_height+self.ypad
        limit=self.total_width
        for o in range(self.max_ordinal, self.min_ordinal-1, -1):
            x=self.days_start+(o-self.min_ordinal)*self.day_width
            if x <= limit:
                d=date.fromordinal(o)
                i,e=self._text_extent(c, d.isoformat())
                w=e[2]
                self._text(c, x-w+self.day_width, y, d.isoformat())
                c.rectangle(x, y-self.ypad,
                            self.day_width, self.ypad)
                c.fill()
                limit=x-w-self.xpad

    def _render_backups(self, c):
        """Render the date backups

        Arguments:
        c -- cairo context"""
        # TODO some kind of legend for the backups wouldn't go amiss
        for backup in self.backups:
            row=self.hv_to_row["%s:%s" % (backup.host, backup.volume)]
            col=date.fromtimestamp(backup.time).toordinal()-self.min_ordinal
            device_index=self.device_to_index[backup.device]
            c.set_source_rgb(*self.device_colors[device_index])
            c.rectangle(self.days_start+col*self.day_width,
                        row*self.row_height+device_index*self.device_indicator_height,
                        self.day_width,
                        self.device_indicator_height)
            c.fill()

    def _render_device_key(self, c):
        """Render the device key

        Arguments:
        c -- cairo context"""
        device_index=0
        for device_index in range(0,len(self.device_list)):
            device=self.device_list[device_index]
            y=self.device_key_y+device_index*self.max_device_height
            c.set_source_rgb(*self.foreground_color)
            self._text(c, self.device_key_x, y, device)
            c.set_source_rgb(*self.device_colors[device_index])
            y+=int((self.max_device_height-self.device_indicator_height)/2)
            c.rectangle(self.device_key_x+self.max_device_width+self.xpad, y,
                        self.device_key_indicator_width, self.device_indicator_height)
            c.fill()

    def render(self, c, render=True):
        """Render the entire layout to a surface

        Arguments:
        c -- cairo context
        render -- True to render, False to just calculate extents

        Returns:
        width, height -- Size of layout"""
        self._ranges()
        self._extents_row_labels(c)
        self._extents_rows(c)
        self._extents_device_key(c)
        self._extents_total(c)
        if render:
            self._render_background(c)
            self._render_row_labels(c)
            self._render_date_bars(c)
            self._render_date_labels(c)
            self._render_backups(c)
            self._render_device_key(c)
        return self.total_width, self.total_height

    def render_fitted_image(self):
        """Construct an appropriately size surface and render to that

        Arguments:
        c -- cairo context"""
        s=cairo.ImageSurface(cairo.FORMAT_ARGB32, 640, 480)
        c=pangocairo.CairoContext(cairo.Context(s))
        w,h=backups.render(c, render=False)
        s=cairo.ImageSurface(cairo.FORMAT_ARGB32, w, h)
        c=pangocairo.CairoContext(cairo.Context(s))
        backups.render(c, render=True)
        return s

if __name__ == '__main__':
    backups=Backups()
    surface=backups.render_fitted_image()
    surface.write_to_png("rsbackup.png") # TODO
